import './globals.css';
import NavBar from '@/components/shared/NavBar/NavBar';
import { Inter } from 'next/font/google';
import Providers from '@/providers/Providers';
import Toaster from '@/components/LibraryExports/Toaster';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NextStack',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='dark' className='transition-all'>
      <Providers>
        <body className={inter.className}>
          <NavBar />
          <main className='max-w-6xl mx-auto px-2'>{children}</main>
          <Toaster />
        </body>
      </Providers>
    </html>
  )
}
